### ISSUE TITLE
Implement jupyterhub spawner that can modify shell environment for kernel

### ISSUE THREAD

**Issue by bmcgough** [FredHutch/ls2-notebook#2]
Needed to use Environment Modules as kernels.
Needed to allow users to modify shell environments for their own use.

**Comment by kenjioman** [comment]
I don't know how you're thinking of implementing this, but I'm assuming we will want to allow pairs (groups) of modules to be activated simultaneously -- the specific use case I just thought of would be, for example, if we want to call a specific version of R from within Python, or vice a versa.

**Comment by bmcgough** [comment]
Environment Modules let us do this easily - a module can easily include other modules.

But this requirement may disappear if containerized notebooks end up being the way to go. We can continue to build R, Python, and other packages using EasyBuild, and make them available for gizmo in /app, while also producing container images. We then build Jupyter note book and/or Rstudio layer on top, and launch them from jupyterhub.

Honestly the biggest issue in my mind is how to handle storage of notebooks and data. People want to share, go github integration seems like a good direction. Rstudio has it, but Jupyterhub does not. And I'm not sure that will meet people's requirements as github objects are generally limited to 50GB. Data sets will likely need to be hosted elsewhere... and local file servers are an obvious solution. However, access to NFS server inside containers (especially containers running in AWS or Azure) poses real challenges.
